### ISSUE TITLE
Input displayed as visible when initializing select with value in it

### ISSUE THREAD

**Issue by shillem** [orchidjs/tom-select#26]
When I load a page with preselected value the tomselect seems to show the input field which instead should be hidden.
I initialize the objects - when dom is loaded - with no options:

```
new TomSelect(input, {}); 
```

In the screenshot I have a select with value in it (input that should start as hidden is shown) and another select with no default value selected.

![tom-select](https://user-images.githubusercontent.com/5537484/108505560-e0bd0e00-72b7-11eb-8d1f-0842456f02d8.png)

![tom-select2](https://user-images.githubusercontent.com/5537484/108506168-aacc5980-72b8-11eb-9153-84fb43407143.png)

I notice that `hideInput()` is called in order to set those properties. Maybe, should it be called when initializing the tomselect?

**Comment by oyejorge** [comment]
It's actually left visible intentionally so that the placeholder will display. The tom-select.js.org web page is a good example of this:

![Screenshot_2021-02-19 Tom Select](https://user-images.githubusercontent.com/1043524/108522778-6aee7d80-728a-11eb-8e0f-e36c425aaadf.png)

I can definitely understand the desire to hide it though and it's a [pretty easy customization to make](https://jsfiddle.net/ktje4bu1/1/).

**Comment by shillem** [comment]
Now that you mention placeholder... I just tried to set one and actually the problem disappears.
So it happens only when there's no placeholder set.

So my options to solve the problem are:
1. set a placeholder
2. use `onInitialize` to execute `hideInput`

I'm not sure I understand the logic but I will adapt. Thanks.

**Comment by shillem** [comment]
Anyway, I was still looking at your code snippet and there the problem isn't happening. I think there's something to do with the css rules. I'm using bootstrap 4 and correspondent tomselect bootstrap4 css file.

**Comment by shillem** [comment]
OK, I think I understood. It's a matter of available width for the select. If that is what you meant with your initial answer I apologize. I think that hidden field should overflow instead of trying to display below as a sort of new line.

See this example: https://jsfiddle.net/bw7vx062/

**Comment by oyejorge** [comment]
There's definitely room for improvement. Without placeholder text and smaller width, it doesn't make sense for the hidden field to display below. [We could use flex styles to keep it all on one line](https://jsfiddle.net/4bcx21fe/)

**Comment by shillem** [comment]
Yes, that works!

**Comment by oyejorge** [comment]
One last thought, with v1.2 we now have two plugins for input display:  [dropdown_input](https://tom-select.js.org/plugins/dropdown-input/) and  [input_autogrow](https://tom-select.js.org/plugins/input-autogrow/)

This doesn't mean we're done working on the input display, there's still room for improvement. But since it's a customizable component via plugins, custom CSS and the controlInput setting, it means we have to be careful making changes to the default.
