### ISSUE TITLE
[Bug]: bootstrap 5.3 styles bug

### ISSUE THREAD

**Issue by Datzu712** [orchidjs/tom-select#754]
### Bug description

I'm using bootstrap 5.3.3 with tom select 2.3.1 and when I try to create a select, there is a strange box around the select:
![image](https://github.com/user-attachments/assets/19b610c3-21d7-42e3-ab37-6d6dd16cc9d4)

### Expected behavior

I think it should look something like this for example:
![image](https://github.com/user-attachments/assets/f7654f96-7efe-45ca-8c63-883e739db594)

### Steps to reproduce

You can check what I mean here:
https://codepen.io/Datzu712/pen/zYVdRvo?editors=1000
![image](https://github.com/user-attachments/assets/f0c8cbe9-9745-4efd-a3a6-84b04470910f)

I realized what happens when you put the form-select class in it that weird border appears

### Additional context

- OS: Ubuntu
- Browser: chrome
- Version chrome 127.0.6533.99 / ubuntu 22
- Device: ?

**Comment by xJuvi** [comment]
Hey
it's not a bug. Your use the regular Theme. For bootstrap add bootstrap5 to the css link. You can find the alternative theme files (bootstrap) in the dist folder on jsdelivr. 

After changing the css file to the correct one the select looks like expected. 

Kind regards.

**Comment by body-clock** [comment]
Yeah, I think the [Styling Examples](https://tom-select.js.org/examples/styling/) page on the main site is a little confusing. I don't really understand what it's trying to communicate. Left column with no item styling and right column with item styling? I ran into this same behavior when I was attempting to style with Bootstrap 5. Just import the bootstrap theme CSS instead of the main CSS and you should be good.

**Comment by xJuvi** [comment]
The styling example only show the results from different bootstrap options. The key point which solce your problem is to change the main css against the bootstrap5 css - otherwise the bootstrap styling doesn't take effect.

**Comment by body-clock** [comment]
Yeah, I'm aware - you may be responding to OP and not me, but I do think it's worth mentioning that the styling page leads a new user to believe that they can add these classes to apply the Bootstrap theming. I think, since both me and the other user ran into this issue, there is an opportunity to improve the docs/language on that page to better communicate how to style Tom Select with Bootstrap.
